version: '2'
services:
  science:
    build: ./docker
    ports:
      - "8888:8888"
    volumes:
      - ./docker/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py
      - ./work:/root/work
      